theme: jekyll-theme-minimal
title: Gina R. Bai
email: rbai2@ncsu.edu
paginate: 5

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
